language: c

before_install:
  - curl -L https://github.com/luvit/lit/raw/master/get-lit.sh | sh
  - lit install

script: luvit ./test

env:
  global:
    - PLATFORM=linux
  matrix:
    - LUA=lua5.1
    - LUA=luajit
